language: python
sudo: false
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=py35-pure
env:
    - TOXENV=py27
    - TOXENV=py27-pure
    - TOXENV=pypy
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py34-pure
    - TOXENV=pypy3
    - TOXENV=coverage
    - TOXENV=docs
install:
    - pip install tox
script:
    - tox
notifications:
    email: false
